INSERT INTO `hc_category` VALUES('1','1','content','1','0','0','0','1','1,2,3,4,5','网站介绍','','','','','about','/html/about/','0','0','array (
  \'ishtml\' => \'1\',
  \'template_list\' => \'default\',
  \'page_template\' => \'page\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'\',
  \'repeatchargedays\' => \'1\',
)','1','0','0','wangzhanjieshao','');
INSERT INTO `hc_category` VALUES('2','1','content','1','0','1','0,1','0','2','关于我们','','','','about/','aboutus','/html/about/aboutus/','0','0','array (
  \'ishtml\' => \'1\',
  \'template_list\' => \'default\',
  \'page_template\' => \'page\',
  \'meta_title\' => \'关于我们\',
  \'meta_keywords\' => \'关于我们\',
  \'meta_description\' => \'关于我们\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'\',
  \'repeatchargedays\' => \'1\',
)','1','1','0','guanyuwomen','');
INSERT INTO `hc_category` VALUES('3','1','content','1','0','1','0,1','0','3','联系方式','','','','about/','contactus','/html/about/contactus/','0','0','array (
  \'ishtml\' => \'1\',
  \'template_list\' => \'default\',
  \'page_template\' => \'page\',
  \'meta_title\' => \'联系方式\',
  \'meta_keywords\' => \'联系方式\',
  \'meta_description\' => \'联系方式\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'\',
  \'repeatchargedays\' => \'1\',
)','2','1','0','lianxifangshi','');
INSERT INTO `hc_category` VALUES('4','1','content','1','0','1','0,1','0','4','版权声明','','','','about/','copyright','http://www.hc.com/index.php?m=content&c=index&a=lists&catid=4','0','0','array (
  \'ishtml\' => \'0\',
  \'template_list\' => \'default\',
  \'page_template\' => \'page\',
  \'meta_title\' => \'版权声明\',
  \'meta_keywords\' => \'版权声明\',
  \'meta_description\' => \'版权声明\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'\',
  \'repeatchargedays\' => \'1\',
)','3','1','0','banquanshengming','');
INSERT INTO `hc_category` VALUES('5','1','content','1','0','1','0,1','0','5','招聘信息','','','','about/','hr','/html/about/hr/','0','0','array (
  \'ishtml\' => \'1\',
  \'template_list\' => \'default\',
  \'page_template\' => \'page\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'\',
  \'repeatchargedays\' => \'1\',
)','4','1','0','zhaopinxinxi','');
INSERT INTO `hc_category` VALUES('13','1','content','0','1','10','','0','','行业洞察','','','','','IndustryNews','','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'hucai\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','0','1','0','','');
INSERT INTO `hc_category` VALUES('11','1','content','0','1','10','0,10','0','11','虎彩新闻','','','','News/','HucaiNews','http://www.hc.com/index.php?m=content&c=index&a=lists&catid=11','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'hucai\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','11','1','0','hucaixinwen','');
INSERT INTO `hc_category` VALUES('12','1','content','0','1','10','','0','','产品动态','','','','','ProductNews','','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'hucai\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','0','1','0','','');
INSERT INTO `hc_category` VALUES('10','1','content','0','1','0','0','1','10,11','新闻中心','','','','','News','http://www.hc.com/index.php?m=content&c=index&a=lists&catid=10','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'hucai\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','10','1','0','xinwenzhongxin','');
