<?php
return array (
  1 => 
  array (
    'modelid' => '1',
    'siteid' => '1',
    'name' => '文章模型',
    'description' => '',
    'tablename' => 'news',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category',
    'list_template' => 'list',
    'show_template' => 'show',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  2 => 
  array (
    'modelid' => '2',
    'siteid' => '1',
    'name' => '下载模型',
    'description' => '',
    'tablename' => 'download',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category_download',
    'list_template' => 'list_download',
    'show_template' => 'show_download',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  3 => 
  array (
    'modelid' => '3',
    'siteid' => '1',
    'name' => '图片模型',
    'description' => '',
    'tablename' => 'picture',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category_picture',
    'list_template' => 'list_picture',
    'show_template' => 'show_picture',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  11 => 
  array (
    'modelid' => '11',
    'siteid' => '1',
    'name' => '视频模型',
    'description' => '',
    'tablename' => 'video',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category_video',
    'list_template' => 'list_video',
    'show_template' => 'show_video',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  12 => 
  array (
    'modelid' => '12',
    'siteid' => '1',
    'name' => '产品',
    'description' => '产品',
    'tablename' => 'product',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'hucai',
    'category_template' => 'category_picture',
    'list_template' => 'list_picture',
    'show_template' => 'show_picture',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  16 => 
  array (
    'modelid' => '16',
    'siteid' => '1',
    'name' => '线上定制',
    'description' => '线上定制',
    'tablename' => 'custom_ol',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'hucai',
    'category_template' => 'category_custom',
    'list_template' => 'list_custom',
    'show_template' => 'show_custom',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  17 => 
  array (
    'modelid' => '17',
    'siteid' => '1',
    'name' => '连锁门店',
    'description' => '影像连锁门店',
    'tablename' => 'link_store',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'hucai',
    'category_template' => 'category',
    'list_template' => 'list',
    'show_template' => 'show',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  15 => 
  array (
    'modelid' => '15',
    'siteid' => '1',
    'name' => '品牌活动',
    'description' => '品牌活动模型',
    'tablename' => 'brand_activity',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'hucai',
    'category_template' => 'category_brand',
    'list_template' => 'list_brand',
    'show_template' => 'show_brand',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
);
?>